[package]
productName = "eve-ui-sync"
version = "0.0.1"

[build]
withGlobalTauri = true
devPath = "../src"
distDir = "../src"

[[tauri.windows]]
fullscreen = false
width = 800
height = 600
resizable = true
title = "eve-ui-sync"


