[package]
productName = "eve-ui-sync"
version = "0.0.1"

[build]
withGlobalTauri = true
devPath = "../src"
distDir = "../src"

[[tauri.windows]]
fullscreen = false
width = 1200
height = 900
resizable = true
title = "EVE UI Sync 0.0.1"


